# ==== Plugins ====
autoload -Uz compinit
compinit

# ==== Configuration ====
zstyle ':completion:*' menu select

# ==== Aliases ====
alias '..'='cd ..'
alias 'g'='git'
alias 'ls'='ls --color'
alias 'l'='ls'
alias 'll'='ls -l'
alias 'vi'='nvim'

# ==== Environment ====
PROMPT='%F{green}%# %1~ %F{255}'
EDITOR='neovim'

