services:

  postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - ~/.local/share/concourse/data:/opt/postgres/data:rw
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: concourse
      PGDATA: /opt/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concourse_user -d concourse"]
      interval: 3s
      timeout: 3s
      retries: 5

  concourse-web:
    image: concourse/concourse:7
    command: web
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ~/.local/share/concourse/keys/:/opt/concourse/keys/:ro
    ports:
      - 8080:8080
    environment:
      CONCOURSE_POSTGRES_HOST: postgres
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_SESSION_SIGNING_KEY: /opt/concourse/keys/session
      CONCOURSE_TSA_HOST_KEY: /opt/concourse/keys/host
      CONCOURSE_TSA_AUTHORIZED_KEYS: /opt/concourse/keys/worker.pub

  concourse-worker:
    image: concourse/concourse:7
    command: worker
    privileged: true
    restart: always
    depends_on:
      - concourse-web
    volumes:
      - ~/.local/share/concourse/keys/:/opt/concourse/keys/:ro
    environment:
      CONCOURSE_WORK_DIR: /opt/concourse/worker
      CONCOURSE_TSA_HOST: concourse-web:2222
      CONCOURSE_TSA_PUBLIC_KEY: /opt/concourse/keys/host.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /opt/concourse/keys/worker

